### ISSUE TITLE
AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by gfrankliu** [bear/s3scan#5]
python s3scan.py 
gives
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the GetBucketAcl operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
Any ideas?

**Comment by bear** [comment]
@gfrankliu the most recent code has the fix for this.

**Comment by gfrankliu** [comment]
I just pulled the new code and tried again (python s3scan.py), but got below error:
botocore.exceptions.ProfileNotFound: The config profile (default) could not be found

BTW, I am not sure ~/.aws but only env vars: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. It used to work before today's change.

**Comment by bear** [comment]
@gfrankliu I made the default value for the profile 'None' - can you give it a try?

If it works then close the issue, otherwise I'll get an environment setup that doesn't use AWS profiles to test.

**Comment by gfrankliu** [comment]
Yes, that works. Thanks!

**Comment by bear** [comment]
@gfrankliu cool! thanks for reporting the bug!
